version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase
    versions:
    - 8.2.4
    - 8.2.5
    - 8.2.8
    - 8.3.2
    - 8.3.3
  - dependency-name: firebase-tools
    versions:
    - 9.2.2
    - 9.4.0
    - 9.6.0
    - 9.7.0
    - 9.9.0
  - dependency-name: antd
    versions:
    - 4.11.2
    - 4.12.1
    - 4.14.1
  - dependency-name: react-scripts
    versions:
    - 4.0.2
    - 4.0.3
